### ISSUE TITLE
Can you write a complete forwarding logic

### ISSUE THREAD

**Issue by shrkx** [emiago/sipgo#162] opened 2024-12-06 01:01 UTC
srv.OnInvite(func(req *sip.Request, tx sip.ServerTransaction) {
		fmt.Println("拨打电话的操作:", req)
		to_user := s.findTargetDevice(req)
		if to_user == nil {
			// 如果目标设备不存在，则返回 404 Not Found,返回到拨打电话端
			tx.Respond(sip.NewResponseFromRequest(req, 404, "Not Found", nil))
			return
		}
		req.SetDestination(to_user.Source)
		txA, err2 := client.TransactionRequest(ctx, req) // Send request and get client transaction handle
		if err2 != nil {
			tx.Respond(sip.NewResponseFromRequest(req, 500, "Internal Server Error", nil))
			return
		}
		defer txA.Terminate() // Client Transaction must be terminated for cleanup
		select {
		case res := <-txA.Responses():
			// Handle responses
			if res.StatusCode == 200 {
				// 发送 200 OK 响应
				tx.Respond(sip.NewResponseFromRequest(req, 200, "OK", res.Body()))
			} else if res.StatusCode == 486 {
				// 处理 486 Busy Here 响应
				tx.Respond(sip.NewResponseFromRequest(req, 486, "Busy Here", nil))
			} else if res.StatusCode == 480 {
				// 处理 480 Temporarily Unavailable 响应
				tx.Respond(sip.NewResponseFromRequest(req, 480, "Temporarily Unavailable", nil))
			} else {
				// 其他错误响应  Other error responses
				tx.Respond(sip.NewResponseFromRequest(req, 500, "Internal Server Error", nil))
			}
		case <-txA.Done():
			// Handle transaction termination
			return
		case <-time.After(time.Second * 5): // 超时处理
			tx.Respond(sip.NewResponseFromRequest(req, 504, "Server Timeout", nil))
			return
		}
	})

After using forwarding, the caller is prompted directly： [8:38:14]  Internal Server Error

May I ask how to optimize the code? Thank you

**Comment by leeyongda** [comment] 2024-12-06 04:25
```go
else if res.StatusCode == 1xx  {
      //  100 Trying
      //  183 Session in Progress
}  else {
     // 其他错误响应  Other error responses
    tx.Respond(sip.NewResponseFromRequest(req, 500, "Internal Server Error", nil))
}
```

**Comment by shrkx** [comment] 2024-12-06 06:52
srv.OnInvite(func(req *sip.Request, tx sip.ServerTransaction) {
		fmt.Println("拨打电话的操作:", req)
		to_user := s.findTargetDevice(req)
		if to_user == nil {
			tx.Respond(sip.NewResponseFromRequest(req, 404, "Not Found", nil))
			return
		}
		req.SetDestination(to_user.Source)               // 用户的源地址   User's source address
		txA, err2 := client.TransactionRequest(ctx, req) // Send request and get client transaction handle
		if err2 != nil {
			fmt.Println("500  Error sending INVITE request:", err2)
			tx.Respond(sip.NewResponseFromRequest(req, 500, "Internal Server Error", nil))
			return
		}
		tx.Respond(sip.NewResponseFromRequest(req, 100, "Trying", nil))
		defer txA.Terminate() // Client Transaction must be terminated for cleanup
		select {
		case res := <-txA.Responses():
			fmt.Println("res.StatusCode:", res.StatusCode)
			// Handle responses
			if res.StatusCode == 100 {
				tx.Respond(sip.NewResponseFromRequest(req, 100, "Trying", nil))
			} else if res.StatusCode == 200 {
				// 发送 200 OK 响应
				fmt.Println("200 OK response received from:", res.From().Address.User, res.Body())
				tx.Respond(sip.NewResponseFromRequest(req, 200, "OK", res.Body()))
			} else if res.StatusCode == 486 {
				// 处理 486 Busy Here 响应
				fmt.Sprintf("486 目标设备 %s 忙碌，无法接听呼叫\n", to_user.Username)
				tx.Respond(sip.NewResponseFromRequest(req, 486, "Busy Here", nil))
			} else if res.StatusCode == 480 {
				// 处理 480 Temporarily Unavailable 响应
				fmt.Sprintf("480 目标设备 %s 忙碌，无法接听呼叫 \n", to_user.Username)
				tx.Respond(sip.NewResponseFromRequest(req, 480, "Temporarily Unavailable", nil))
			} else {
				// 其他错误响应
				fmt.Sprintf("500 目标设备 %s 忙碌，无法接听呼叫 \n", to_user.Username)
				tx.Respond(sip.NewResponseFromRequest(req, 500, "Internal Server Error", nil))
			}
		case <-txA.Done():
			fmt.Println("Transaction terminated")
			// Handle transaction termination
			return
		case <-time.After(time.Second * 5): // 超时处理
			tx.Respond(sip.NewResponseFromRequest(req, 504, "Server Timeout", nil))
			return
		}
	})
Question: After forwarding, only one message is obtained, and the rest cannot be obtained. Why is this?
![1733467927388](https://github.com/user-attachments/assets/01ebfd68-20d4-438b-9672-32a9207d4077)

**Comment by leeyongda** [comment] 2024-12-06 09:33
```go
defer txA.Terminate() // Client Transaction must be terminated for cleanup
for 
   select {
	case res := <-txA.Responses():
		fmt.Println("res.StatusCode:", res.StatusCode)
		// Handle responses
		if res.StatusCode == 100 {
			tx.Respond(sip.NewResponseFromRequest(req, 100, "Trying", nil))
		} else if res.StatusCode == 200 {
			// 发送 200 OK 响应
			fmt.Println("200 OK response received from:", res.From().Address.User, res.Body())
			tx.Respond(sip.NewResponseFromRequest(req, 200, "OK", res.Body()))
		} else if res.StatusCode == 486 {
			// 处理 486 Busy Here 响应
			fmt.Sprintf("486 目标设备 %s 忙碌，无法接听呼叫\n", to_user.Username)
			tx.Respond(sip.NewResponseFromRequest(req, 486, "Busy Here", nil))
		} else if res.StatusCode == 480 {
			// 处理 480 Temporarily Unavailable 响应
			fmt.Sprintf("480 目标设备 %s 忙碌，无法接听呼叫 \n", to_user.Username)
			tx.Respond(sip.NewResponseFromRequest(req, 480, "Temporarily Unavailable", nil))
		} else {
			// 其他错误响应
			fmt.Sprintf("500 目标设备 %s 忙碌，无法接听呼叫 \n", to_user.Username)
			tx.Respond(sip.NewResponseFromRequest(req, 500, "Internal Server Error", nil))
		}
	case <-txA.Done():
		fmt.Println("Transaction terminated")
		// Handle transaction termination
		return
	case <-time.After(time.Second * 5): // 超时处理
		tx.Respond(sip.NewResponseFromRequest(req, 504, "Server Timeout", nil))
		return
	}

}
```

**Comment by emiago** [comment] 2024-12-10 22:03
Hi @shrkx. Why are you timeouting transactions so low? Leave that to SIP timers.

**Comment by shrkx** [comment] 2024-12-18 06:55
Is this the way to use it?

func (r *Router) ForwardSignalingMessageWithWait(request *sip.Request, toUser string, timeout time.Duration) error {
	// 获取用户
	user, err := r.GetUser(toUser)
	if err != nil {
		return fmt.Errorf("failed to get user %s: %v", toUser, err)
	}

	// 获取对话
	dialog, err := r.GetDialog(user)
	if err != nil {
		return fmt.Errorf("failed to get dialog for user %s: %v", toUser, err)
	}

	// 创建带有超时的 context
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	// 启动 SIP 请求的发送
	session, err := dialog.WriteInvite(ctx, request)
	if err != nil {
		return fmt.Errorf("failed to send invite to user %s: %v", toUser, err)
	}

	// 等待响应
	err = session.WaitAnswer(ctx, sipgo.AnswerOptions{})
	if err != nil {
		// 响应超时或发生其他错误
		session.Close() // 确保会话被关闭
		return fmt.Errorf("failed to wait for response from user %s: %v", toUser, err)
	}
	// 如果收到响应，转发响应
	response := session.InviteResponse // 假设 `Response()` 获取的是响应
	if response != nil {
		// 例如：检查响应状态码
		if response.StatusCode == 200 {
			// 如果是 200 OK 响应，进行处理
			fmt.Println(fmt.Printf("Received 200 OK from user %s", toUser))
		} else {
			// 其他响应（如 4xx 或 5xx 系列）
			fmt.Println(fmt.Printf("Received response with status %d from user %s", response.StatusCode, toUser))
		}

		// 转发响应到其他用户
		err := r.ForwardResponse(response, toUser)
		if err != nil {
			fmt.Println(fmt.Printf("Failed to forward response to other user: %v", err))
			session.Close() // 确保会话被关闭
			return err
		}
	}

	// 如果收到响应，打印日志并返回
	session.Close() // 确保会话被关闭
	return nil
}

**Comment by shrkx** [comment] 2024-12-19 12:13
// 注册 INVITE 请求处理程序 => 处理 SIP 呼叫请求
	var inviteHandler = func(req *sip.Request, tx sip.ServerTransaction) {
		go func() {
			// 这里处理媒体信息或其他业务逻辑
			// 例如，您可以在这里进行SDP解析或创建RTP流
			mediaInfo, err := parseSDP(string(req.Body()))
			if err != nil {
				log.Printf("Error parsing SDP: %v", err)
				// 这里可以选择发送失败响应或其他处理
				return
			}

			// 模拟处理媒体流
			fmt.Printf("Processing media info: IP %s, Port %d\n", mediaInfo.AudioIP, mediaInfo.AudioPort)

			// 在这里可以启动处理RTP流等工作
			stream := createRTPStream(mediaInfo.AudioIP, mediaInfo.AudioPort)
			if stream == nil {
				log.Println("Error creating RTP stream")
				return
			}
			processRTPStream(stream)
		}()
		// 路由请求
		route(req, tx)
}
May I ask if using RTP to listen to streams in SIP will affect communication between SIPs? How should I listen properly?

**Comment by emiago** [comment] 2024-12-19 18:58
Hi @shrkx please switch to diago for media things. This project is out of scope of lib. I guess your initial issue is now solved?

**Comment by shrkx** [comment] 2024-12-20 06:22
Yes, the routing forwarding issue has been resolved, but I still want to interpret the voice flow between both parties now

**Comment by shrkx** [comment] 2024-12-20 06:46
May I ask for some ideas or examples? Thank you very much

**Comment by emiago** [comment] 2024-12-22 04:42
Hi @shrkx SIP and media control is seperated by diago, by design. 
You can do whatever you want with audio streaming, and it solves many problems for you like dealing with RTP or SIP.
Still it allows you to go low level as much as you want. 
Closing this as initial issue was resolved. Please try diago, and open issue there for media, just have a look on docs before.

**Closed by emiago** 2024-12-22 04:42 UTC
